### ISSUE TITLE
welcome embed error

### ISSUE THREAD

**Issue by remixllmaf** [Yakiyo/saki#23]
Raw query failed. Code: `unknown`. Message: `Command failed (AtlasError): empty database name not allowed
        at c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:704
        at c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:1763
        at c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:1181
        at mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/proxy_session.go:371
        at mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/proxy_session.go:131
        at mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/session.go:177
        at mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/server.go:280
        at src/runtime/asm_arm64.s:1172)`
    at Pn.handleRequestError (C:\Users\dell\Desktop\saki\node_modules\@prisma\client\runtime\library.js:171:6929)
    at Pn.handleAndLogRequestError (C:\Users\dell\Desktop\saki\node_modules\@prisma\client\runtime\library.js:171:6358)
    at Pn.request (C:\Users\dell\Desktop\saki\node_modules\@prisma\client\runtime\library.js:171:6237) {
  code: 'P2010',
  clientVersion: '4.14.0',
  meta: {
    code: 'unknown',
    message: 'Command failed (AtlasError): empty database name not allowed\n' +
      '\tat c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:704\n' +
      '\tat c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:1763\n' +
      '\tat c011d66f42ef93c352bdc551ec4a2f33/atlasproxy/session_proxy.go:1181\n' +
      '\tat mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/proxy_session.go:371\n' +
      '\tat mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/proxy_session.go:131\n' +
      '\tat mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/session.go:177\n' +
      '\tat mongodb/mongonet@v0.0.0-20230315164131-aac06ecdb659/server.go:280\n' +
      '\tat src/runtime/asm_arm64.s:1172)'
  }
}

**Comment by Yakiyo** [comment]
Not sure what ur exactly trying to do from the context but the issue is most probably coming from ur DATABASE_URL env. Prisma requires you to specify the database name in ur database url.

Related issue on the prisma repo: [`prisma/prisma#6726`](https://github.com/prisma/prisma/issues/6726), check this [comment](https://github.com/prisma/prisma/issues/6726#issuecomment-825047867)

Your url should contain the db name as in: `mongodb://aaa:bbb@ccc.mongo.net/YOUR_DB_NAME_HERE?retryWrites=true&w=majority`
